name: Android sdk docker image
on:
  push:
    branches: [ "main" ]
  #   Publish semver tags as releases.
    tags: [ 'v*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        jdk:
          - "eclipse-temurin:8-jdk-jammy"
          - "eclipse-temurin:11-jdk-jammy"
          - "eclipse-temurin:17-jdk-jammy"
        ANDROID_COMPILE_SDK:
          - "31"
          - "29"
        ANDROID_BUILD_TOOLS:
          - "30.0.2"
          - "30.0.3"
          - "29.0.2"
        ANDROID_SDK_TOOLS:
          - "6514223"
        ANDROID_NDK:
          - "21.0.6113669"
          - "21.4.7075529"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag name
        id: gentag
        run: |
          TAG="${{ matrix.jdk }}-${{ matrix.ANDROID_COMPILE_SDK }}-${{ matrix.ANDROID_BUILD_TOOLS }}-${{ matrix.ANDROID_SDK_TOOLS }}-${{ matrix.ANDROID_NDK }}"
          TAG=$(echo "$TAG" | sed "s/:/-/g")
          echo $TAG
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.gentag.outputs.TAG }}
          build-args: |
            ANDROID_COMPILE_SDK=${{ matrix.ANDROID_COMPILE_SDK }}
            ANDROID_BUILD_TOOLS=${{ matrix.ANDROID_BUILD_TOOLS }}
            ANDROID_SDK_TOOLS=${{ matrix.ANDROID_SDK_TOOLS }}
            JDK_IMAGE=${{ matrix.jdk }}
            ANDROID_NDK=${{ matrix.ANDROID_NDK }}
